# Generated by Django 4.0 on 2021-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_name', models.ImageField(blank=True, null=True, upload_to='')),
                ('demo_link', models.CharField(max_length=500)),
                ('source_code', models.CharField(max_length=500)),
            ],
        ),
    ]
