# Generated by Django 4.0 on 2021-12-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='demo',
        ),
    ]
